CREATE TABLE loan_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    minimum_amount DECIMAL(19,2) NOT NULL,
    maximum_amount DECIMAL(19,2) NOT NULL,
    tenure_value INTEGER NOT NULL,
    tenure_unit VARCHAR(20) NOT NULL,
    days_after_due_for_fee_application INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE product_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    fee_type VARCHAR(40) NOT NULL,
    calculation_type VARCHAR(40) NOT NULL,
    application_stage VARCHAR(40) NOT NULL,
    fee_value DECIMAL(19,2) NOT NULL,
    trigger_days_after_due INTEGER,
    CONSTRAINT fk_product_fees_product FOREIGN KEY (product_id) REFERENCES loan_products(id)
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(160),
    phone_number VARCHAR(40) NOT NULL,
    date_of_birth DATE,
    loan_limit DECIMAL(19,2) NOT NULL,
    risk_grade VARCHAR(40) NOT NULL,
    preferred_notification_channel VARCHAR(20) NOT NULL
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_number VARCHAR(80) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    structure VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    principal_amount DECIMAL(19,2) NOT NULL,
    outstanding_amount DECIMAL(19,2) NOT NULL,
    total_fees_applied DECIMAL(19,2) NOT NULL,
    origination_date DATE NOT NULL,
    due_date DATE NOT NULL,
    consolidated_due_date DATE,
    consolidated_billing BOOLEAN NOT NULL,
    last_fee_accrual_date DATE,
    late_fee_applied BOOLEAN NOT NULL,
    CONSTRAINT fk_loans_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_loans_product FOREIGN KEY (product_id) REFERENCES loan_products(id)
);

CREATE TABLE loan_installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    installment_number INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount_due DECIMAL(19,2) NOT NULL,
    amount_paid DECIMAL(19,2) NOT NULL,
    paid BOOLEAN NOT NULL,
    CONSTRAINT fk_installments_loan FOREIGN KEY (loan_id) REFERENCES loans(id)
);

CREATE TABLE repayments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    channel VARCHAR(40) NOT NULL,
    external_reference VARCHAR(120) NOT NULL,
    paid_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_repayments_loan FOREIGN KEY (loan_id) REFERENCES loans(id)
);

CREATE TABLE notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(60) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    subject VARCHAR(200),
    body TEXT,
    active BOOLEAN NOT NULL
);

CREATE TABLE notification_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(60) NOT NULL,
    product_code VARCHAR(50),
    customer_segment VARCHAR(40),
    channel VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    loan_id BIGINT,
    event_type VARCHAR(60) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    recipient VARCHAR(160),
    subject VARCHAR(200),
    message TEXT,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP
);

CREATE INDEX idx_loans_status_due_date ON loans(status, due_date);
CREATE INDEX idx_notifications_customer_id ON notifications(customer_id);
